GET  http://localhost:3001/users/
content-type: application/json

{"id": "1"}

###

POST http://localhost:3001/users/
content-type: application/json

{
"lastName":"testing",
"email": "test@gmail.com",
"name":"tested" }

###


DELETE http://localhost:3001/users/
content-type: application/json

{
"id":5 }