GET  http://localhost:3001/users/
content-type: application/json



###

POST http://localhost:3001/users/
content-type: application/json

{
"lastName":"testing",
"email": "testing@gmail.com",
"name":"tested" }

###


DELETE http://localhost:3001/users/28
content-type: application/json

###


PUT http://localhost:3001/users/29
content-type: application/json

{"name": "tes1tings"}